const AUTH_START = "AUTH_START";
const REG_SUCCESS = "REG_SUCCESS";
const REG_FAILED = "REG_FAILED";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILED = "LOGIN_FAILED";
const LOGOUT = "LOGOUT";
